### ISSUE TITLE
Build on Mac

### ISSUE THREAD

**Issue by hoodie** [ascii-dresden/asciii#15]

**Comment by kiliankoe** [comment]
![](http://i.imgur.com/qsdhdjs.gif)

**Comment by hoodie** [comment]
So we can concur that it "builds" on mac. But does it work?

**Comment by hoodie** [comment]
``` rust
let there = Some(Result<Porting::to(Mac)>);
```

**Comment by hoodie** [comment]
Did I mention it works on windows?

**Comment by kiliankoe** [comment]
Problem was a broken config file on my end 😂

**Comment by hoodie** [comment]
@kiliankoe is this can we deliver through brew?

**Comment by kiliankoe** [comment]
✅ 

homebrew works as specified in the readme
