### ISSUE TITLE
JSON Response Format

### ISSUE THREAD

**Issue by V1ncNet** [ascii-dresden/asciii#73]
It'll be nice if the received JSON looks like:

### Multiple _Array_
```json
[
  {
    "id": "project ident",
    "client": { },
    "event": { }
  },
  {
    "id": "project ident",
    "client": { },
  }
]
```
and so on.

### Single _Object_
```json
{
  "id": "project ident",
  "client": { },
  "event": { }
}
```

**Comment by hoodie** [comment]
you essentially mean: "just add the `id` field"?

**Comment by V1ncNet** [comment]
Essentially... Right now it's almost impossible to use the received data.

**Comment by V1ncNet** [comment]
Ups

**Comment by hoodie** [comment]
Look at the current format
